schema = 3

[mod]
  [mod."github.com/amarnathcjd/gogram"]
    version = "v1.3.20"
    hash = "sha256-CKKbQiXX7CDtK8Xx/7URfQo2LN2X+azRaCChLqWGx10="
  [mod."github.com/joho/godotenv"]
    version = "v1.5.1"
    hash = "sha256-kA0osKfsc6Kp+nuGTRJyXZZlJt1D/kuEazKMWYCWcQ8="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."golang.org/x/net"]
    version = "v0.31.0"
    hash = "sha256-G+vGyCnn8jywmX3KvsIwhZkOv3+oAERNNeCeiQqfIL0="
